"""empty message

Revision ID: 2494ac9ab092
Revises: d1e2a770789e
Create Date: 2023-01-10 18:11:30.394643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2494ac9ab092'
down_revision = 'd1e2a770789e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('import_batch_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('import_batch_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
